# Generated by Django 5.0.7 on 2024-09-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='has_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripmember',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
