# Generated by Django 5.0.7 on 2024-09-22 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_trip_has_ended_tripmember_payment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmember',
            name='joined',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tripmember',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pages.trip'),
        ),
    ]
