# Generated by Django 5.0.7 on 2024-09-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_tripmember_joined_alter_tripmember_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripmember',
            name='joined',
        ),
    ]
