# Generated by Django 5.0.7 on 2024-09-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_tripmember_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
